### ISSUE TITLE
Add google analytics.

### ISSUE THREAD

**Issue by aedorado** [aedorado/ext-control-panel#5]
I will provide you with the tracking id if you're up for this one.

**Comment by iGitScor** [comment]
Hi, I'm interested to solve this "issue".

<small>_I also have a suggestion, maybe you could propose a "Create a README.md presentation" issue_</small>

**Comment by aedorado** [comment]
Sure that is a good idea. I'm sorry it doesn't have a contribution or readme file. I will add them shortly. Ok so this is a chrome extension. Fork and try adding Google analytics to it. Send PR if successful.

**Comment by aedorado** [comment]
Thanks again. :)
